/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/gallery/': RouteRecordInfo<'/gallery/', '/gallery', Record<never, never>, Record<never, never>>,
    '/gallery/cloud/': RouteRecordInfo<'/gallery/cloud/', '/gallery/cloud', Record<never, never>, Record<never, never>>,
    '/gallery/mingchaoimgku/': RouteRecordInfo<'/gallery/mingchaoimgku/', '/gallery/mingchaoimgku', Record<never, never>, Record<never, never>>,
    '/gallery/mydogmd/': RouteRecordInfo<'/gallery/mydogmd/', '/gallery/mydogmd', Record<never, never>, Record<never, never>>,
    '/gallery/nezhaghg/': RouteRecordInfo<'/gallery/nezhaghg/', '/gallery/nezhaghg', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/哪吒2影后感': RouteRecordInfo<'/posts/哪吒2影后感', '/posts/哪吒2影后感', Record<never, never>, Record<never, never>>,
    '/posts/松溉古镇游': RouteRecordInfo<'/posts/松溉古镇游', '/posts/松溉古镇游', Record<never, never>, Record<never, never>>,
    '/posts/汪星走好': RouteRecordInfo<'/posts/汪星走好', '/posts/汪星走好', Record<never, never>, Record<never, never>>,
    '/posts/相思之梦': RouteRecordInfo<'/posts/相思之梦', '/posts/相思之梦', Record<never, never>, Record<never, never>>,
    '/posts/新博客新开始': RouteRecordInfo<'/posts/新博客新开始', '/posts/新博客新开始', Record<never, never>, Record<never, never>>,
    '/posts/站长15岁啦': RouteRecordInfo<'/posts/站长15岁啦', '/posts/站长15岁啦', Record<never, never>, Record<never, never>>,
    '/posts/Vue学习之路（1）': RouteRecordInfo<'/posts/Vue学习之路（1）', '/posts/Vue学习之路（1）', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
